const h = require('./mx-patch-helpers.js');
const EM = String.fromCharCode(8212);
h.rep("    window.addEventListener('contextmenu', function (e) {\n      var chatEl = UI.chat;\n      if (!chatEl || !chatEl.contains(e.target)) return;\n      // 1.27.0: ALWAYS swallow the contextmenu inside the chat HUD " + EM + " the game\n      // opens its own player card behind the chat otherwise. With a nick we\n      // show the themed bubble; without one (scrollbar/input/blank) it is just\n      // suppressed.\n      e.preventDefault();\n      e.stopImmediatePropagation();\n      var nick = chatNickFrom(e.target);\n      if (nick) ibubbleShow(nick, e.target);\n    }, true);",
"    function chatRClick(e) {\n      var chatEl = UI.chat;\n      if (!chatEl || !chatEl.contains(e.target)) return;\n      // 1.28.0: ALWAYS swallow right-click inside the chat HUD, on every event\n      // the card can react to (contextmenu, mousedown, mouseup, click) " + EM + " the\n      // game binds more than one of them, which is why the card still slipped\n      // through. With a nick we show the themed bubble; without one the click\n      // is just suppressed.\n      e.preventDefault();\n      e.stopImmediatePropagation();\n      mxCardSweepArm();   // forced removal: kill anything the game already spawned\n      var nick = chatNickFrom(e.target);\n      if (nick) ibubbleShow(nick, e.target);\n    }\n    window.addEventListener('contextmenu', chatRClick, true);\n    window.addEventListener('mousedown', function (e) { if (e.button === 2) chatRClick(e); }, true);\n    window.addEventListener('mouseup', function (e) { if (e.button === 2) chatRClick(e); }, true);\n    window.addEventListener('click', function (e) { if (e.button === 2) chatRClick(e); }, true);",
  '1a all right-click events suppressed');
h.rep("  function wireChatBubble() {",
"  /* 1.28.0: forced native-card sweeper. Suppression alone proved not enough\n   * (the game can open its card from handlers Murther cannot see). After every\n   * right-click inside the chat we snapshot the body's children; for the next\n   * 1.4s a 120ms burst removes any NEW fixed/absolute element that is not ours\n   * and is card-sized. Self-clearing, idle while the tab is hidden (Freebuff\n   * tabs courtesy), never touches large legitimate UI. */\n  var mxCardSweep = { t: 0, until: 0, known: [] };\n  function mxCardSweepArm() {\n    mxCardSweep.known = [].slice.call(DOC.body.children);\n    mxCardSweep.until = Date.now() + 1400;\n    if (!mxCardSweep.t) mxCardSweep.t = setInterval(mxCardSweepTick, 120);\n    mxCardSweepTick();\n  }\n  function mxCardSweepTick() {\n    if (DOC.hidden) return;\n    if (Date.now() > mxCardSweep.until) { clearInterval(mxCardSweep.t); mxCardSweep.t = 0; return; }\n    [].slice.call(DOC.body.children).forEach(function (nd) {\n      if (mxCardSweep.known.indexOf(nd) !== -1) return;\n      if (nd.id === 'murther-root' || nd.id === 'mx-boot-cover') return;\n      var cn = String(nd.className || '');\n      if (cn.indexOf('mx-') === 0) return;\n      var cs = null;\n      try { cs = getComputedStyle(nd); } catch (e) { return; }\n      if (!cs || (cs.position !== 'fixed' && cs.position !== 'absolute')) return;\n      if (nd.offsetWidth > 460 || nd.offsetHeight > 460) return;\n      try { nd.remove(); } catch (e2) {}\n    });\n  }\n  function wireChatBubble() {",
  '1b sweeper engine inserted');
h.saveNow();
console.log('P1 SAVED');
