const h = require('./mx-patch-helpers.js');
// 3c: replace the old arrow block with the redesigned axis guide (hold-only)
h.cut("    if (S.game.lsArrows && fxMouse.has) {\n      var dx = fxMouse.x - cx, dy = fxMouse.y - cy;\n",
"      x.restore();\n    }\n",
"    if (lsState.active && S.game.lsArrows !== false && fxMouse.has) {\n      // v1.28.0 redesign: a split-axis GUIDE through the cursor " + String.fromCharCode(8212) + " one horizontal\n      // and one vertical hairline spanning the arena, gradient-faded at the\n      // ends so the split plane reads at a glance, arrowheads riding each\n      // axis near the mouse, and a small ring at the exact cursor point.\n      var gx = fxMouse.x, gy = fxMouse.y;\n      var col = S.game.lsArrowColor || fxLineColor();\n      x.save();\n      x.lineWidth = 2; x.lineCap = 'butt';\n      function axisGrad(x0, y0, x1, y1) {\n        var g = x.createLinearGradient(x0, y0, x1, y1);\n        g.addColorStop(0, 'rgba(0,0,0,0)');\n        g.addColorStop(0.5, col);\n        g.addColorStop(1, 'rgba(0,0,0,0)');\n        return g;\n      }\n      x.globalAlpha = 0.85;\n      x.strokeStyle = axisGrad(0, gy, w, gy);\n      x.beginPath(); x.moveTo(0, gy); x.lineTo(w, gy); x.stroke();\n      x.strokeStyle = axisGrad(gx, 0, gx, h);\n      x.beginPath(); x.moveTo(gx, 0); x.lineTo(gx, h); x.stroke();\n      function axisHead(hx, hy, dxh, dyh) {\n        var wg = 7;\n        x.beginPath();\n        x.moveTo(hx + dxh * 10, hy + dyh * 10);\n        x.lineTo(hx - dyh * wg - dxh * 2, hy + dxh * wg - dyh * 2);\n        x.moveTo(hx + dxh * 10, hy + dyh * 10);\n        x.lineTo(hx + dyh * wg - dxh * 2, hy - dxh * wg - dyh * 2);\n        x.stroke();\n      }\n      x.globalAlpha = 0.95;\n      axisHead(gx - 46, gy, -1, 0); axisHead(gx + 46, gy, 1, 0);\n      axisHead(gx, gy - 46, 0, -1); axisHead(gx, gy + 46, 0, 1);\n      x.globalAlpha = 0.9;\n      x.strokeStyle = col;\n      x.beginPath(); x.arc(gx, gy, 5, 0, 6.2832); x.stroke();\n      x.restore();\n    }\n",
  '3c axis guide replaces arrows');
// 3d: keydown activates on the game's linesplit keys
h.rep("      if (keyMatches(e, S.keys.cursorLine)) { S.game.cursorLine = !S.game.cursorLine; setGame('cursorLine', S.game.cursorLine); fxKick(); toast(S.game.cursorLine ? 'Cursor line on' : 'Cursor line off'); return; }",
"      // v1.28.0: the guide follows the GAME's linesplit key (hold): down shows\n      // it, releasing (or Esc / death) hides it. Nothing draws without the key.\n      var lsc = lsCodes();\n      if (lsc.length && lsc.indexOf(e.keyCode) !== -1 && !e.repeat) {\n        lsState.active = true; fxKick();\n      }\n      if (keyMatches(e, S.keys.cursorLine)) { S.game.cursorLine = !S.game.cursorLine; setGame('cursorLine', S.game.cursorLine); fxKick(); toast(S.game.cursorLine ? 'Cursor line on' : 'Cursor line off'); return; }",
  '3d keydown activates');
h.saveNow();
console.log('P3b SAVED');
